spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

jpa:
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  hibernate:
    ddl-auto: create

kakao:
  api:
    url: "https://dapi.kakao.com"
    key: "6194547d698099dfcc05445572a66bbb"